#!/bin/bash

echo "Introduce el nombre del directorio: "
read dir
echo "Introduce una palabra: "
read palabra

if [[ -e $dir ]] 
then
	cd $dir
	ls -l > fichero1
	while IFS=read -r 1 2 3 4 5 6 7 8 9
		grep -r -i $palabra $dir
else
	echo -e "Lo siento, el directorio no existe :( \nAdiós"
	exit
fi
